export const defaultLegitimation = {
  formType: 'joint-affidavit',
  // Child
  childFirst: '',
  childMiddle: '',
  childLast: '',
  dateOfBirth: '',
  sex: '',
  placeOfBirthStreet: '',
  placeOfBirthCity: '',
  placeOfBirthProvince: '',
  // Parents
  motherFirst: '',
  motherMiddle: '',
  motherLast: '',
  motherCitizenship: '',
  fatherFirst: '',
  fatherMiddle: '',
  fatherLast: '',
  fatherCitizenship: '',
  // Marriage
  marriageRegistryNo: '',
  dateOfMarriage: '',
  placeOfMarriageCity: '',
  placeOfMarriageProvince: '',
  placeOfMarriageCountry: '',
  solemnizingOfficer: '',
  // Affidavit of legitimation
  affidavitLegitRegistryNo: '',
  affidavitLegitDate: '',
  // Affidavit of acknowledgement (Item 8)
  affidavitAckRegistryNo: '',
  affidavitAckDate: '',
  // COLB of child
  colbRegistryNo: '',
  colbRegDate: '',
  colbPageNo: '',
  colbBookNo: '',
  // Questions
  birthRegisteredIligan: 'YES',
  acknowledgedByFatherInColb: 'YES',
  parentsMinorAtBirth: 'NO',
  bothParentsAlive: 'YES',
  // Surviving / deceased parent (when applicable)
  survivingParentFirst: '',
  survivingParentMiddle: '',
  survivingParentLast: '',
  survivingParentCitizenship: '',
  deceasedParentFirst: '',
  deceasedParentMiddle: '',
  deceasedParentLast: '',
  dateOfDeath: '',
  // Print
  certificateIssuanceDate: '',
  cityCivilRegistrarName: '',
  recipientName: '',
  recipientTitle: '',
  recipientOffice: '',
  recipientAgency: '',
  transmittalDate: '',
  transmittalSalutation: '',
  transmittalSignatoryName: '',
  transmittalSignatoryTitle: '',
  contactPhone: '',
  contactEmail: '',
}
