export const defaultAUSF = {
  formType: 'ausf-0-6',
  applicantName: '',
  civilStatus: 'single',
  relationshipToChild: '',
  birthRegisteredInIligan: 'YES',
  childAlreadyAcknowledged: 'NO',
  motherFirst: '',
  motherMiddle: '',
  motherLast: '',
  motherCitizenship: 'Filipino',
  fatherFirst: '',
  fatherMiddle: '',
  fatherLast: '',
  fatherCitizenship: 'Filipino',
  childFirst: '',
  childMiddle: '',
  childLast: '',
  dateOfBirth: '',
  age: '',
  sex: 'MALE',
  placeOfBirthAddress: '',
  placeOfBirthCity: 'ILIGAN CITY',
  placeOfBirthProvince: 'LANAO DEL NORTE',
  colbRegistryNo: '',
  colbDateOfRegistration: '',
  colbPageNumber: '',
  colbBookNumber: '',
  ausfRegistryNo: '',
  ausfDateOfRegistration: '',
  ackRegistryNo: '',
  ackDateOfRegistration: '',
  publicDocRegistryNo: '',
  publicDocDate: '',
  publicDocOffice: '',
  filingLocation: 'ILIGAN CITY',
  affidavitExecutionDate: '',
  cityCivilRegistrarName: 'Atty. Yussif Don Justin F. Martil',
  certificateSignatoryName: 'LORELIE L. CANTO',
  certificateSignatoryTitle: '',
  regAusfSignatoryName: '',
  regAusfSignatoryTitle: '',
  regAckSignatoryName: '',
  regAckSignatoryTitle: '',
  transmittalLocalSignatoryName: '',
  transmittalLocalSignatoryTitle: '',
  transmittalOotSignatoryName: '',
  transmittalOotSignatoryTitle: '',
  lcrAckSignatoryName: '',
  lcrAckSignatoryTitle: '',
  lcrNotAckSignatoryName: '',
  lcrNotAckSignatoryTitle: '',
  certificateIssuanceDate: '',
  contactPhone: '228-1311',
  contactEmail: 'civilregistrar.iligan@gmail.com',
  // Certificate of Live Birth (Annotation / Municipal Form 102)
  motherReligion: '',
  motherOccupation: '',
  motherAge: '',
  motherResidence: '',
  motherTotalChildrenAlive: '',
  motherChildrenLiving: '',
  motherChildrenDead: '',
  fatherReligion: '',
  fatherOccupation: '',
  fatherAge: '',
  fatherResidence: '',
  typeOfBirth: 'SINGLE',
  birthOrder: '',
  birthWeight: '',
  colbRegistryNoForm102: '',
  attendantName: '',
  attendantTitle: '',
  attendantAddress: '',
  attendantDate: '',
  informantName: '',
  informantRelationship: '',
  informantAddress: '',
  informantDate: '',
  preparedByName: '',
  preparedByTitle: '',
  preparedByDate: '',
  receivedByName: '',
  receivedByTitle: '',
  receivedByDate: '',
  registeredByName: '',
  registeredByTitle: '',
  registeredByDate: '',
  /** When true (child not acknowledged), print view offers Out-of-Town Transmittal only; when false, local Transmittal only. */
  ausfTransmittalIsOutOfTown: false,
  // Transmittal (5.2, 6) — default local addressee (AUSF transmittal letter)
  transmittalDate: '',
  recipientName: 'KANYE WEST',
  recipientTitle: 'LAAGAN',
  recipientOffice: 'ILIGAN CITY, ILIGAN',
  transmittalSignatoryName: '',
  transmittalSignatoryTitle: '',
  // Annotation (Child Ack): COLB scan and annotation text
  colbScanDataUrl: '',
  annotationChildAckText: '',
  annotationChildNotAckText: '',
  // Separate COLB scan per view so upload in one does not show in the other
  colbScanDataUrlAck: '',
  colbScanDataUrlNotAck: '',
}

/** Align out-of-town toggle with saved transmittal form type (legacy rows may omit the flag). */
export function syncAusfTransmittalFlagWithFormType(data) {
  if (!data || typeof data !== 'object') return data
  if (data.formType === 'out-of-town') return { ...data, ausfTransmittalIsOutOfTown: true }
  if (data.formType === 'child-not-ack-transmittal') return { ...data, ausfTransmittalIsOutOfTown: false }
  return data
}
