export const defaultAUSF = {
  formType: 'ausf-0-6',
  applicantName: '',
  civilStatus: 'single',
  relationshipToChild: '',
  birthRegisteredInIligan: 'YES',
  childAlreadyAcknowledged: 'NO',
  motherFirst: '',
  motherMiddle: '',
  motherLast: '',
  motherCitizenship: 'Filipino',
  fatherFirst: '',
  fatherMiddle: '',
  fatherLast: '',
  fatherCitizenship: 'Filipino',
  childFirst: '',
  childMiddle: '',
  childLast: '',
  dateOfBirth: '',
  age: '',
  sex: 'MALE',
  placeOfBirthAddress: '',
  placeOfBirthCity: 'ILIGAN CITY',
  placeOfBirthProvince: 'LANAO DEL NORTE',
  colbRegistryNo: '',
  colbDateOfRegistration: '',
  colbPageNumber: '',
  colbBookNumber: '',
  ausfRegistryNo: '',
  ausfDateOfRegistration: '',
  ackRegistryNo: '',
  ackDateOfRegistration: '',
  publicDocRegistryNo: '',
  publicDocDate: '',
  publicDocOffice: '',
  filingLocation: 'ILIGAN CITY',
  affidavitExecutionDate: '',
  cityCivilRegistrarName: 'Atty. Yussif Don Justin F. Martil',
  certificateSignatoryName: 'LORELIE L. CANTO',
  certificateIssuanceDate: '',
  contactPhone: '(063) 224-5038',
  contactEmail: 'civilregistrar.iligan@gmail.com',
  // Certificate of Live Birth (Annotation / Municipal Form 102)
  motherReligion: '',
  motherOccupation: '',
  motherAge: '',
  motherResidence: '',
  motherTotalChildrenAlive: '',
  motherChildrenLiving: '',
  motherChildrenDead: '',
  fatherReligion: '',
  fatherOccupation: '',
  fatherAge: '',
  fatherResidence: '',
  typeOfBirth: 'SINGLE',
  birthOrder: '',
  birthWeight: '',
  colbRegistryNoForm102: '',
  attendantName: '',
  attendantTitle: '',
  attendantAddress: '',
  attendantDate: '',
  informantName: '',
  informantRelationship: '',
  informantAddress: '',
  informantDate: '',
  preparedByName: '',
  preparedByTitle: '',
  preparedByDate: '',
  receivedByName: '',
  receivedByTitle: '',
  receivedByDate: '',
  registeredByName: '',
  registeredByTitle: '',
  registeredByDate: '',
  // Transmittal (5.2, 6)
  transmittalDate: '',
  recipientName: '',
  recipientTitle: '',
  recipientOffice: '',
  transmittalSignatoryName: '',
  // Annotation (Child Ack): COLB scan and annotation text
  colbScanDataUrl: '',
  annotationChildAckText: '',
  // Separate COLB scan per view so upload in one does not show in the other
  colbScanDataUrlAck: '',
  colbScanDataUrlNotAck: '',
}
