export const defaultCourtDecree = {
  formType: 'cert-authenticity',
  // Section 1: What country issued the court order/decree
  country: 'PHILIPPINES',
  courtOrRacco: '',
  // Section 2: Affected civil document
  affectedDocument: 'MARRIAGE_CERTIFICATE',
  // Section 3: Document owner/s
  documentOwnerName: '',
  // Section 4: Court decree details
  dateIssued: '',
  courtThatIssued: '',
  issuedByTitle: 'Judge',
  issuedByName: '',
  typeOfCase: 'Civil Case No.',
  caseNo: '',
  authenticatedBy: '',
  registryNumber: '',
  dateRegistered: '',
  caseTitle: '',
  // For print: issuance date and signatory (optional)
  certificateIssuanceDate: '',
  cityCivilRegistrarName: '',
  // Transmittal recipient (optional)
  recipientName: '',
  recipientTitle: '',
  recipientOffice: '',
  // LCR Form 1A table-only (court decree) — one field per printed row
  lcr1aRegistryNumber: '',
  lcr1aDateRegistration: '',
  lcr1aNameOfChild: '',
  lcr1aSex: '',
  lcr1aDateOfBirth: '',
  lcr1aPlaceOfBirth: '',
  lcr1aNameOfMother: '',
  lcr1aMotherCitizenship: 'FILIPINO',
  lcr1aNameOfFather: '',
  lcr1aFatherCitizenship: 'FILIPINO',
  lcr1aDateMarriageParents: '',
  lcr1aPlaceMarriageParents: '',
  // LCR Form 3A table-only (marriage)
  lcr3aHusbandName: '',
  lcr3aHusbandDobAge: '',
  lcr3aHusbandCitizenship: 'FILIPINO',
  lcr3aHusbandCivilStatus: 'SINGLE',
  lcr3aHusbandMother: '',
  lcr3aHusbandFather: '',
  lcr3aWifeName: '',
  lcr3aWifeDobAge: '',
  lcr3aWifeCitizenship: 'FILIPINO',
  lcr3aWifeCivilStatus: 'SINGLE',
  lcr3aWifeMother: '',
  lcr3aWifeFather: '',
  lcr3aRegistryNumber: '',
  lcr3aDateRegistration: '',
  lcr3aDateMarriage: '',
  lcr3aPlaceMarriage: '',
  /** LCR 3A: husband/wife DOB (ISO yyyy-mm-dd) + optional age — used for print table */
  husbandDateOfBirth: '',
  wifeDateOfBirth: '',
  husbandAge: '',
  wifeAge: '',
  /** Print: marriage annotation — 'nullity' | 'divorce' | 'art42' */
  marriageAnnotationMode: 'nullity',
  marriageNullityScanDataUrl: '',
  // LCR Form 2A table-only (death)
  lcr2aRegistryNumber: '',
  lcr2aDateRegistration: '',
  lcr2aNameDeceased: '',
  lcr2aSex: '',
  lcr2aCivilStatus: '',
  lcr2aCitizenship: 'FILIPINO',
  lcr2aDateDeath: '',
  lcr2aCitizenshipFather: 'FILIPINO',
  lcr2aPlaceDeath: '',
  lcr2aCauseDeath: '',
  // Legacy keys (older drafts / legitimation merge)
  colbRegistryNo: '',
  colbRegDate: '',
  childFirst: '',
  childMiddle: '',
  childLast: '',
  dateOfBirth: '',
  sex: '',
  placeOfBirthStreet: '',
  placeOfBirthCity: '',
  placeOfBirthProvince: '',
  motherFirst: '',
  motherMiddle: '',
  motherLast: '',
  motherCitizenship: 'FILIPINO',
  fatherFirst: '',
  fatherMiddle: '',
  fatherLast: '',
  fatherCitizenship: 'FILIPINO',
  dateOfMarriage: '',
  placeOfMarriageOfParents: '',
  lcrForm1aRemarks: '',
  certificateSignatoryName: 'SHIRLY L. DEMECILLO',
  contactPhone: '(063) 227 - 2806',
  contactEmail: 'civilregistrar.iligan@gmail.com',
}
