export const defaultCourtDecree = {
  formType: 'cert-authenticity',
  // Section 1: What country issued the court order/decree
  country: 'PHILIPPINES',
  courtOrRacco: '',
  // Section 2: Affected civil document
  affectedDocument: 'MARRIAGE_CERTIFICATE',
  affectedDocuments: ['MARRIAGE_CERTIFICATE'],
  // Section 3: Document owner/s
  documentOwnerName: '',
  // Section 4: Court decree details
  dateIssued: '',
  courtThatIssued: '',
  issuedByTitle: 'Judge',
  issuedByName: '',
  typeOfCase: 'Civil Case No.',
  caseNo: '',
  authenticatedBy: '',
  registryNumber: '',
  dateRegistered: '',
  caseTitle: '',
  // For print: issuance date and signatory (optional)
  certificateIssuanceDate: '',
  cityCivilRegistrarName: '',
  // Transmittal recipient (optional)
  recipientName: '',
  recipientTitle: '',
  recipientOffice: '',
  transmittalOotLine4: '',
  transmittalOotLine5: '',
  transmittalOotLine6: '',
  /** When true, print offers Out-of-Town Transmittal only; when false, local Transmittal only. */
  courtDecreeTransmittalIsOutOfTown: false,
  /** Local transmittal “To PSA” block (6 lines); empty = use print defaults */
  transmittalToPsaLine1: '',
  transmittalToPsaLine2: '',
  transmittalToPsaLine3: '',
  transmittalToPsaLine4: '',
  transmittalToPsaLine5: '',
  transmittalToPsaLine6: '',
  transmittalAttnPrefix: '',
  transmittalAttnLine1: '',
  transmittalAttnLine2: '',
  transmittalAttnLine3: '',
  // LCR Form 1A table-only (court decree) — one field per printed row
  lcr1aRegistryNumber: '',
  lcr1aDateRegistration: '',
  lcr1aNameOfChild: '',
  lcr1aSex: '',
  lcr1aDateOfBirth: '',
  lcr1aPlaceOfBirth: '',
  lcr1aNameOfMother: '',
  lcr1aMotherCitizenship: 'FILIPINO',
  lcr1aNameOfFather: '',
  lcr1aFatherCitizenship: 'FILIPINO',
  lcr1aDateMarriageParents: '',
  lcr1aPlaceMarriageParents: '',
  /** LCR 1A print: COLB page/book (section 2 — overrides shared colbPageNo/colbBookNo on 1A only) */
  lcr1aColbPageNo: '',
  lcr1aColbBookNo: '',
  // LCR Form 3A table-only (marriage)
  lcr3aHusbandName: '',
  lcr3aHusbandDobAge: '',
  lcr3aHusbandCitizenship: 'FILIPINO',
  lcr3aHusbandCivilStatus: 'SINGLE',
  lcr3aHusbandMother: '',
  lcr3aHusbandFather: '',
  lcr3aWifeName: '',
  lcr3aWifeDobAge: '',
  lcr3aWifeCitizenship: 'FILIPINO',
  lcr3aWifeCivilStatus: 'SINGLE',
  lcr3aWifeMother: '',
  lcr3aWifeFather: '',
  lcr3aRegistryNumber: '',
  lcr3aDateRegistration: '',
  lcr3aDateMarriage: '',
  lcr3aPlaceMarriage: '',
  /** LCR 3A print: COLB page/book */
  lcr3aColbPageNo: '',
  lcr3aColbBookNo: '',
  /** LCR 3A: husband/wife DOB (ISO yyyy-mm-dd) + optional age — used for print table */
  husbandDateOfBirth: '',
  wifeDateOfBirth: '',
  husbandAge: '',
  wifeAge: '',
  /** Print: marriage annotation — 'nullity' | 'divorce' | 'art42' */
  marriageAnnotationMode: 'nullity',
  marriageNullityScanDataUrl: '',
  // LCR Form 2A table-only (death)
  lcr2aRegistryNumber: '',
  lcr2aDateRegistration: '',
  lcr2aNameDeceased: '',
  lcr2aSex: '',
  lcr2aCivilStatus: '',
  lcr2aCitizenship: 'FILIPINO',
  lcr2aDateDeath: '',
  lcr2aCitizenshipFather: 'FILIPINO',
  lcr2aPlaceDeath: '',
  lcr2aCauseDeath: '',
  /** LCR 2A print: COLB page/book */
  lcr2aColbPageNo: '',
  lcr2aColbBookNo: '',
  // Legacy keys (older drafts / legitimation merge)
  colbPageNo: '',
  colbBookNo: '',
  colbRegistryNo: '',
  colbRegDate: '',
  childFirst: '',
  childMiddle: '',
  childLast: '',
  dateOfBirth: '',
  sex: '',
  placeOfBirthStreet: '',
  placeOfBirthCity: '',
  placeOfBirthProvince: '',
  motherFirst: '',
  motherMiddle: '',
  motherLast: '',
  motherCitizenship: 'FILIPINO',
  fatherFirst: '',
  fatherMiddle: '',
  fatherLast: '',
  fatherCitizenship: 'FILIPINO',
  dateOfMarriage: '',
  placeOfMarriageOfParents: '',
  lcrForm1aRemarks: '',
  lcrForm1aRemarksTouched: false,
  lcrForm2aRemarks: '',
  lcrForm2aRemarksTouched: false,
  lcrForm3aRemarks: '',
  lcrForm3aRemarksTouched: false,
  certificateSignatoryName: '',
  certificateSignatoryTitle: '',
  cityCivilRegistrarTitle: '',
  /** Court decree transmittal “Respectfully yours” block — synced with CCR roster in print sidebar */
  transmittalSignatoryName: '',
  transmittalSignatoryTitle: '',
  ccrScopeLcr1aName: '',
  ccrScopeLcr1aTitle: '',
  ccrScopeLcr2aName: '',
  ccrScopeLcr2aTitle: '',
  ccrScopeLcr3aName: '',
  ccrScopeLcr3aTitle: '',
  /** Bold phrase in LCR “issued upon the request of …”. Empty = 1A default OCRG/OWNER/…; 2A/3A default OCRG/DOCUMENT OWNER unless set. */
  lcrCertificationRequestParty: '',
  /** Printed font size (pt) for LCR / annotation remarks body text. */
  lcrRemarksFontSizePt: '12',
  contactPhone: '228-1311',
  contactEmail: 'civilregistrar.iligan@gmail.com',
}

/** Align out-of-town flag with legacy print formType when loading drafts. */
export function syncCourtDecreeTransmittalFlagFromFormType(data) {
  if (!data || typeof data !== 'object') return data
  if (data.formType === 'out-of-town-transmittal') return { ...data, courtDecreeTransmittalIsOutOfTown: true }
  if (data.formType === 'transmittal') return { ...data, courtDecreeTransmittalIsOutOfTown: false }
  return data
}
